zephyr/Kconfig: remove SINGLE_IMAGE_DFU duplication
nrfconnect/sdk-mcuboot pull request #119
Opened 2020-09-09 09:08 UTC by nvlsianpu

SINGLE_IMAGE_DFU option is already defined in boot/zephyr/Kconfig.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

2020-09-09 09:44 UTC, MarekPieta approved these changes

2020-09-09 09:47 UTC, de-nordic approved these changes

2020-09-09 09:55 UTC, hakonfam requested changes
Missing sauce tag

2020-09-09 11:09 UTC, de-nordic commented
> 
> Missing sauce tag
??

2020-09-09 11:17 UTC, hakonfam commented
> > Missing sauce tag
> 
> ??

Sorry for not being clear.

The commit message must be prefixed with [nrf noup/toup/fromlist] to indicate its relationship with upstream.

2020-09-09 11:24 UTC, de-nordic commented
> 
> The commit message must be prefixed with [nrf noup/toup/fromlist] to indicate its relationship with upstream.

Ah that thing. I thought that there is another phrase I do not understand,

2020-09-09 11:33 UTC, hakonfam approved these changes

2020-09-28 09:36 UTC, hakonfam requested changes
While you are here, could you remove the duplicate entry for BOOT_SIGNATURE_KEY_FILE as well?

```
diff --git a/zephyr/Kconfig b/zephyr/Kconfig
index 142d3cc..5d1502e 100644
--- a/zephyr/Kconfig
+++ b/zephyr/Kconfig
@@ -35,19 +35,6 @@ config MCUBOOT_FLASH_WRITE_BLOCK_SIZE
 
 endif # BOOTLOADER_MCUBOOT
 
-config BOOT_SIGNATURE_KEY_FILE
-       string "PEM key file"
-       default "root-rsa-2048.pem"
-       help
-         You can use either absolute or relative path.
-         In case relative path is used, the build system assumes that it starts
-         from the directory where the MCUBoot KConfig configuration file is
-         located. If the key file is not there, the build system uses relative
-         path that starts from the MCUBoot repository root directory.
-         The key file will be parsed by imgtool's getpub command and a .c source
-         with the public key information will be written in a format expected by
-         MCUboot.
-
 config DT_FLASH_WRITE_BLOCK_SIZE
        int
        default $(dt_node_int_prop_int,$(DT_CHOSEN_ZEPHYR_FLASH),write-block-size)

```

2020-09-28 11:00 UTC, nvlsianpu commented
@hakonfam ^^ ok will do

2020-09-29 10:18 UTC, nvlsianpu commented
@hakonfam done

2020-09-29 10:22 UTC, NordicBuilder commented
**Some checks failed. Please fix and resubmit.**

## Gitlint issues

Commit 33bb23b617:
1: UC5 Title exceeds max length (73>72): "[nrf noup] Kconfig: move BOOT_SIGNATURE_KEY_FILE to its upstream location"



*Tip: The bot edits this comment instead of posting a new one, so you can check the comment's history to see earlier messages.*

2020-10-01 12:19 UTC, hakonfam approved these changes

2020-10-08 06:56 UTC, merged