Upmerge 2020 09 16
nrfconnect/sdk-mcuboot pull request #120
Opened 2020-09-16 09:18 UTC by tejlmand

2020-09-16 09:23 UTC, NordicBuilder commented
**Some checks failed. Please fix and resubmit.**

## Gitlint issues

Commit ba7748d092:
1: UC3 Title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "Convert from Zephyr to C99 types"

Commit e88113bbeb:
1: UC6 Body has no content, should at least have 1 line.

Commit 014f42df09:
1: UC5 Title exceeds max length (78>72): "zephyr: Replace DT_FLASH_DEV_NAME with DT_CHOSEN_ZEPHYR_FLASH_CONTROLLER_LABEL"



*Tip: The bot edits this comment instead of posting a new one, so you can check the comment's history to see earlier messages.*

2020-09-16 11:09 UTC, nvlsianpu requested changes

2020-09-16 12:22 UTC, tejlmand commented on boot/zephyr/CMakeLists.txt
> +  message("MCUBoot bootloader key file: ${KEY_FILE}")
fixed.

2020-09-23 12:20 UTC, nvlsianpu approved these changes

2020-10-01 19:33 UTC, nvlsianpu approved these changes

2020-10-06 14:39 UTC, merged