[nrf noup] Kconfig: create duplicate of sign key
nrfconnect/sdk-mcuboot pull request #129
Opened 2020-10-27 07:04 UTC by hakonfam

This duplicate is needed for the parent image to have access
to the signing key when MCUBoot is not built from source.

Ref: NCSDK-6859
Signed-off-by: Håkon Øye Amundsen <haakon.amundsen@nordicsemi.no>

2020-10-27 07:06 UTC, hakonfam commented
This is needed since I asked @nvlsianpu to remove the duplicate here: https://github.com/nrfconnect/sdk-mcuboot/pull/119#pullrequestreview-497344313

@mbolivar-nordic  I was thinking about leveraging the kconfig variable introduced to solve the same issue with `west sign` but my gut feeling was to revert this change, since its how it used to work before. Any thoughts?

2020-10-28 03:37 UTC, mbolivar-nordic commented
>  Any thoughts?

I'm really losing the bubble on what's going on with these; let's talk offline

2020-11-05 15:17 UTC, tejlmand requested changes
I would prefer to revert all NCS specific patches, like: https://github.com/nrfconnect/sdk-mcuboot/commit/04514d6a2236050ac8abd89d72f59dd175a0265e regarding Kconfig changes, and move all the Kconfig logic into https://github.com/nrfconnect/sdk-nrf

Will be happy to assist on that work if you agree.

2020-11-20 08:53 UTC, hakonfam commented
Note to self, verify that the new solution sets the default value in the application.
This can be done building a project with MCUBOOT without setting the key explitcitly.

2020-12-21 11:31 UTC, hakonfam commented
Will be fixed using MODULE_ROOT functionality.

2020-12-21 11:31 UTC, closed without merging