Upmerge 171120
nrfconnect/sdk-mcuboot pull request #130
Opened 2020-11-18 14:24 UTC by ioannisg

2020-11-18 14:37 UTC, NordicBuilder commented
**Some checks failed. Please fix and resubmit.**

## Nits issues

```
Please remove blank lines at end of 'boot/cypress/platforms/retarget_io_pdl/cy_retarget_io_pdl.h'

Please remove blank lines at start of 'boot/zephyr/include/arm_cleanup.h'
```

## Gitlint issues

Commit 6610e880d8:
1: UC2 Signed-off-by: must have a full name

Commit 907476d701:
4: UC4 Line exceeds max length (74>72): "might cause linking collision as this header belongs to `FIH_ENABLE_DELAY`"
6: UC4 Line exceeds max length (73>72): "This header is already included by "bootutil/fault_injection_hardening.h""

Commit fce873364e:
5: UC4 Line exceeds max length (73>72): "fault injection like clock or power glitching, EM pulse, laser beam, etc."

Commit 1dcc73b0b8:
1: UC3 Title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "Add ifdefs in crypto abstract function for ec256 to enable compilation when mbedtls used as backend"
1: UC5 Title exceeds max length (99>72): "Add ifdefs in crypto abstract function for ec256 to enable compilation when mbedtls used as backend"
1: UC6 Body has no content, should at least have 1 line.

Commit 8ebe53537b:
5: UC4 Line exceeds max length (74>72): "when running through recommonmark==0.6.0 because it is unable to parse the"

Commit 6ea44be64f:
1: UC5 Title exceeds max length (78>72): "cypress: update user documentation with disclaimer and additional instructions"
3: UC4 Line exceeds max length (127>72): "This change adds Disclaimer section to Cypress related documentation and adds details about custom hardware configuration flow."

Commit ff026122e1:
3: UC4 Line exceeds max length (244>72): "Entering deep sleep on CM0 without valid application on CM4 caused pyocd error while programming. This fix disables entering deep sleep mode on CM0 if no valid applications found for boot. Waiting for uart complete tx reworked. Code refactoring"

Commit 8097d86b2f:
1: UC3 Title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "Compile with MBEDTLS_CIPHER_MODE_CTR set."
1: UC6 Body has no content, should at least have 1 line.

Commit 4f4833d465:
1: UC3 Title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "Abstracting mcuboot crypto functions for cleaner porting and less of an ifdef hell."
1: UC5 Title exceeds max length (83>72): "Abstracting mcuboot crypto functions for cleaner porting and less of an ifdef hell."
10: UC4 Line exceeds max length (81>72): "- No need to free contexts because Zephyr sets MBEDTLS_PLATFORM_NO_STD_FUNCTIONS."

Commit f62ea0c464:
1: UC3 Title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "bootutil *should not* import assert.h"

Commit 453231ca12:
1: UC3 Title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "Remove unused headers."
1: UC6 Body has no content, should at least have 1 line.

Commit 30feaf648d:
1: UC3 Title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "hal_flash is unused, remove the import."

Commit 8672c8e98a:
1: UC2 Signed-off-by: must have a full name

Commit 42b32394d6:
3: UC4 Line exceeds max length (86>72): "Fix imgtool does not take into account value of confirm flag, when signing .hex images"

Commit fdff3e1ea0:
4: UC4 Line exceeds max length (73>72): "of Zephyr are confused. It might be might be understood as one-pair image"

Commit 9ed399cd6d:
1: UC5 Title exceeds max length (93>72): "zephyr: Turn off cache for Cortex M7 before chain-loading. The new image will fail otherwise."
1: UC6 Body has no content, should at least have 1 line.

## pylint issues

```
************* Module imgtool.image
scripts/imgtool/image.py:222:55: C0303: Trailing whitespace (trailing-whitespace)
scripts/imgtool/image.py:253:4: R0201: Method could be a function (no-self-use)
scripts/imgtool/image.py:491:4: R0201: Method could be a function (no-self-use)
```

## Identity/Emails issues

6dfba7fd0736f0e6bf92e921e498108b3caa653e: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

a022053a4173084880bc48bdd4bbcf9607274ead: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

a08d7f5d00f3f1a0231938569e6e7cfaedc88858: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

7adcc8e1103eb2ef1102bdc43cc91b0e87fdd0b8: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

d3c55689113c3688f6d3d655bb7091a86ebe69d6: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

49a9acbab9cb713dd6e239b8d84c7b1423b2edf2: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

ee7909cc72bcc475e4d0f378c12049378d766d4d: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

5bafddc597203ba3368777db52b1ffaf6d6d65b9: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

905d64c9749c9a2071d1fe4d7276ec3f616c2166: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

bc1a7347531106b2a20b832394e749830576aad2: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

cfe3a1f501cd5d14f7e680ee76d8010ee09de7f7: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

8ef73b07e7bde81101449a69786416da023cbd9b: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

c5617751123c426bfc315e4c70f644c699288979: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

aeae31691f588c3951aca332bc8811dee30c5899: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

b0b2797347a47e3819cd0fe0997a2af63d3d2601: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

e02d22a4ab8ade69c4a77d3a2739c9ab6e496ee3: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

d133ca23423b86e668c9f640afa1d0b1598ecf27: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

d4f41ec02a11e4098e0a6eddb8e06aec5b5d6a45: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

51163770a42616c4c707917b9fedf8c7cd130274: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

0cb278157ed9573611b3ceae20e0b0574607fc0d: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

c6afb6e3b8767baece3f1438a5b0a9f7e1362382: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

552b8680cec7e651c3da8b0c42eb8ea5a4dc801e: author email (Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>) needs to match one of the signed-off-by entries.

6610e880d825630c43dda57ab22f693a938fd525: author email (TTornblom <thomas.tornblom@iar.com>) does not follow the syntax: First Last <email>.

8672c8e98a173415e838b91bab967b8e5619975a: author email (dmiv <dmiv@cypress.com>) does not follow the syntax: First Last <email>.



*Tip: The bot edits this comment instead of posting a new one, so you can check the comment's history to see earlier messages.*

2020-11-19 09:28 UTC, ioannisg commented
Comments:
FYI @mbolivar-nordic  @hakonfam @sigvartmh @nvlsianpu @carlescufi 

- 64617d8 was pushed, so we are able to also revert 80eb854, which was not caught by ncs-compare, although a relevant patch was merged upstream.
- 026a4e5, 75fd8f2, 01dd7b3, ac05701, 22373ec are standard git-reverts, so the corresponding reverted commits must be reapplied as is.
- 06d7123 is a **_manual revert_** I did, to be able to achieve a conflict-free upmerge. Without it, I would have to revert, again, the commit by Sebastian B, that introduces PM (along with several other dependencies); this way we minimize the effort in next up-merges. However, the reverts done in  06d7123  must be re-applied.

2020-11-19 17:59 UTC, mbolivar-nordic requested changes
>     * I would have to revert, again, the commit by Sebastian B, that introduces PM (along with several other dependencies)

If that's what it takes, that's what has to be done. 

Here is the `west ncs-loot -z 35264cc214 mcuboot` output for this PR right now:

```
- 7718705e8b500aabbfa1cc720f082bfc048bb9f5 [nrf noup] ci: add Jenkins-based CI for NCS
- 228e8868663ce009c6b1d1a18315ef3c5d75b105 [nrf toup] zephyr: add support for Thingy:91
- 45f0833a8dee3549ef661137dd03e54d180ae8d8 [nrf noup] zephyr: Remove duplication from Kconfig and cmake
- 68f2bcc798113500cf4abf50af6e6def60ba384a [nrf noup] boot: bootutil: Add shared crypto functions for ECDSA
- e6e68505af12b6288da5b7215662bd711ec6e9c0 [nrf noup] boot: zephyr: Call fw_info_ext_api_provide() before booting
- 04514d6a2236050ac8abd89d72f59dd175a0265e [nrf noup] treewide: add NCS partition manager support
- 59e02e27dafd41456c54bf45d0b2d95ab15b6e0f [nrf noup] zephyr: lock mcuboot using fprotect before jumping
- f35f763bbe7e698b3c275c548faae3537061e9c7 [nrf noup] boot: zephyr: nrf53 network core bootloader implementation
- 1788ad7a9894780bf27c68d98aa87e833f170c7d [nrf noup] kconfig: use cc310 for ecdsa by default
- 4d1b74b32f7f49692fc40132c7c5e84030ef6a85 [nrf noup] kconfig: enable external crypto config
- 74e2e0f30c4e48738dd5014bd88d31f90d00f9c5 [nrf fromtree] zephyr: Fix serial recovery compilation warnings
- 54238adc9a5912ace04b35c8a642faa1e731fa74 [nrf fromtree] boot: zephyr: reset SPLIM registers before boot
- 45a94cb234ec33a015677f106cbb937b6ff81569 [nrf fromtree] boot: zephyr: Disable HW stack protection
- d0634dd15ca4541a93bc22d9e1aa0fad07e95bc0 [nrf fromtree] doc: fix link to external page in PORTING
- 80eb85475da3d3a8408170523e7cb6d1063a9757 [nrf fromtree] kconfig: zephyr: provide logic ...
- 32640591847ec648fb5b0cee85c9dc57db7cb3bf [nrf fromtree] bootutil: fix swap-move brick with padded image0
- 931d96b455c536fbd33e50b27f89aa384b054590 [nrf fromtree] bootutil: fix boostrapping in swap-move
- 02833faca1a373767c67aed29df5eb9e0cfbc9fd [nrf fromlist] zephyr: update name of nrf5340 dk
- b03e43f31a96619287bbd0b43545152f17eab0b6 [nrf fromlist] zephyr: enable progressive erase on all nRF boards
- a8213955e7113e3dcc23f17318829dc6b695ce67 [nrf fromlist] doc: clean up multi-image documentation
- 85645596570de42cda3cfd60a0cc5d02813947af [nrf fromlist] bootutil: copy image size with fast overwrite
- e9d64d45865fdd4943a01f55c5096643c399d52a [nrf temphack] Kconfig: add accessor for flash write block size
- a8cc9879747019ba0459b900920296365abae4b1 [nrf temphack] do_boot: clean peripherals state before boot
- 4c5ff85bbd6f218147cc4f29641e88957ad09a64 [nrf temphack] boot: bootutil: Word align read buffer in loader
- ac052356a507e309d9da7246f3c16dde4d46aea3 [nrf temphack] Kconfig: select 8-bits flash access for recovery mode
```

And the upstream commit that's being merged in is `5a6e181`. If you try to cherry pick the `ncs-loot` output onto `5a6e181` in order, you get a conflict ... at the partition manager support patch:

```
CONFLICT (content): Merge conflict in boot/zephyr/CMakeLists.txt
error: could not apply 04514d6... [nrf noup] treewide: add NCS partition manager support
```

> this way we minimize the effort in next up-merges. 

The point of revert-and-reapply is not to minimize effort in the next upmerge, it's to make sure that the tree can be rebased into a linear history at any time.

2020-11-20 13:18 UTC, ioannisg commented
> If that's what it takes, that's what has to be done.

@mbolivar-nordic I am not sure I fully-agree; I think we "could" try to be a bit smarter here. The optimization problem is
```
minimize the number of reverted commits
subject to: linear history, conflict-free merges, etc.
```

If we are able to push a "noup" commit that makes us revert less stuff in the next upmerge, we could exploit in case-by-case basis. But I don't have a super strong opinion. I also see the value of a standardized procedure.

So I followed the recommendation and reverted all commits that conflict (along with their dependencies).

2020-11-20 13:21 UTC, ioannisg commented
@hakonfam , @nvlsianpu all patches starting from ac05235 need to be re-applied, _unless_ you think they are not needed any more. In that case please, add a comment for each one that is left behind.

2020-11-20 13:22 UTC, ioannisg commented
I mean, ac05235,  4c5ff85, a8cc987 and onwards.

2020-11-23 08:41 UTC, nvlsianpu commented
https://github.com/nrfconnect/sdk-mcuboot/pull/130/commits/9f3d9db74473f94a38e62e43e8253ab25a006d2a should be left behind.
https://github.com/nrfconnect/sdk-mcuboot/pull/130/commits/f48de7a5237886a994984528b1cb1fb595620e1b removes need for it.

2020-11-23 08:46 UTC, ioannisg commented on boot/bootutil/src/loader.c
> +        int rc = flash_area_open(flash_area_id_from_multi_image_slot(
Fine with me. Can yo squash this then?

2020-11-23 09:32 UTC, hakonfam commented
> [9f3d9db](https://github.com/nrfconnect/sdk-mcuboot/commit/9f3d9db74473f94a38e62e43e8253ab25a006d2a) should be left behind.
> [f48de7a](https://github.com/nrfconnect/sdk-mcuboot/commit/f48de7a5237886a994984528b1cb1fb595620e1b) removes need for it.
> 
> same [3ab66d8](https://github.com/nrfconnect/sdk-mcuboot/commit/3ab66d826fe5d98a69047ce1f0e0cdd3dff70888) - , can be removed, all flash drivers supports unaligned reads since a while.

This should be fixed now.

2020-11-23 10:10 UTC, nvlsianpu approved these changes
The upmerge process was done properly

2020-11-23 13:35 UTC, de-nordic approved these changes
Looks OK.
Manually tested CONFIG_SINGLE_APPLICATIONS_SLOT and it works OK.

2020-11-23 15:17 UTC, mbolivar-nordic requested changes
I'm still seeing conflicts when I try to rebase.

west ncs-loot says:

```
NCS commit (manifest-rev): 4b41ab6ccaee6c54f37d351b51b85f94499459f7, upstream commit: c71d2186077f9fd5f6d1aa53ee3f09dc41ce78f6
OOT patches: 13 total
- 7718705e8b500aabbfa1cc720f082bfc048bb9f5 [nrf noup] ci: add Jenkins-based CI for NCS
- 228e8868663ce009c6b1d1a18315ef3c5d75b105 [nrf toup] zephyr: add support for Thingy:91
- e6e68505af12b6288da5b7215662bd711ec6e9c0 [nrf noup] boot: zephyr: Call fw_info_ext_api_provide() before booting
- 59f2d3ca15ce58d2e5ef22f2db6bec48f82e6a00 [nrf noup]: remove unnecessary default value
- 7888f0ad4df6eb10fd8c732cb84656a4e7030ad1 [nrf noup] zephyr: Remove duplication from Kconfig and cmake
- f20a1a1c10e3949d1d12bd0621518eccb4cd69f2 [nrf noup] boot: bootutil: Add shared crypto for ECDSA and SHA
- 069b603167a1e8f1491e44139dc099c8065fdf28 [nrf noup] treewide: add NCS partition manager support
- c21b25a9a8f60fa2e10c820be0166ac87de52fdf [nrf noup] zephyr: lock mcuboot using fprotect before jumping
- 3d745d389b10beb1e333a8ea65d3590c2f06b965 [nrf temphack] Kconfig: add accessor for flash write block size
- 337357898d46250584c2d400ea3ae57770ae99b8 [nrf noup] boot: zephyr: nrf53 network core bootloader implementation
- 5e0fc4ec914b0765920c00a994f3dd30c93e4136 [nrf noup] kconfig: use cc310 for ecdsa by default
- a2c9384795e897f52f5eee840ac63f04633335f3 [nrf noup] kconfig: enable external crypto config
- 4b41ab6ccaee6c54f37d351b51b85f94499459f7 [nrf temphack] do_boot: clean peripherals state before boot
```

And I get a different conflict when I cherry-pick:

```

CONFLICT (content): Merge conflict in boot/zephyr/Kconfig
error: could not apply 59f2d3c... [nrf noup]: remove unnecessary default value
```

I'll keep looking into this after codeowners meeting, but want to put a -1 on this again until we get the PR rebasable.

2020-11-23 16:25 UTC, mbolivar-nordic commented
We can just skip the conflicting patch during the cherry-pick and we get a zero-diff rebase, which I have posted here:

https://github.com/mbolivar-nordic/sdk-mcuboot/tree/upmerge-130-rebase

This has an empty diff with the current tip of this PR, 4b41ab6.

I think we could make an exception and allow this PR to be merged if we make it very clear in the commit log for the conflicting patch that it is a 'temphack' which should be skipped when rebasing. That won't cause difficulties when it is time to rebase for the next NCS release.

2020-11-23 18:54 UTC, mbolivar-nordic approved these changes

2020-11-26 20:41 UTC, utzig approved these changes

2020-11-27 18:53 UTC, merged