boot/zephyr: Kconfig changes to use RSA boot signature for thingy91
nrfconnect/sdk-mcuboot pull request #153
Opened 2021-05-25 07:51 UTC by balaji-nordic

The bootloader that is factory-programmed on thing91 does not support ECDSA
signature type. Hence this commit sets the signature type to RSA for
applications built for thing91.

Fixes CIA-259

Signed-off-by: Balaji Srinivasan <balaji.srinivasan@nordicsemi.no>

2021-06-07 13:32 UTC, nvlsianpu approved these changes

2021-06-16 13:28 UTC, tejlmand requested changes
Should this be a `[nrf noup]`commit ?
To my knowledge, the `BOARD_THINGY91_NRF9160` and `BOARD_THINGY91_NRF52840` boards are not available upstream.

Code changes looks good.

2021-06-17 14:06 UTC, balaji-nordic commented
> Should this be a `[nrf noup]`commit ?
> To my knowledge, the `BOARD_THINGY91_NRF9160` and `BOARD_THINGY91_NRF52840` boards are not available upstream.
> 
> Code changes looks good.

Updated the commit message as suggested.

2021-06-21 15:10 UTC, tejlmand approved these changes

2021-06-24 08:05 UTC, hakonfam approved these changes

2021-06-28 08:50 UTC, merged