cmake: fix for max path length on Windows OS
nrfconnect/sdk-mcuboot pull request #156
Opened 2021-06-15 11:00 UTC by mariuszpos

Fix for max path length on Windows OS.

Signed-off-by: Mariusz Poslinski <mariusz.poslinski@nordicsemi.no>

2021-06-15 12:59 UTC, nvlsianpu requested changes
This should go upstream and be [nrf fromlist] here.

2021-06-16 09:21 UTC, tejlmand commented
@mariuszpos you were requested to make an upstream PR, and then change this into a `[nrf fromlist]`.
You should not close this PR, just rework it according to what was requested.

2021-06-16 10:06 UTC, mariuszpos commented
I've closed this PR because from my observations this fix does not solve the problem completely.

2021-06-16 14:16 UTC, mariuszpos commented
Updated with fix from upstream.

2021-06-16 14:51 UTC, nvlsianpu approved these changes

2021-06-16 14:54 UTC, nvlsianpu requested changes
@mariuszpos You forgot to add [nrf fromtree] tag sauce in the commit message.

2021-06-16 18:51 UTC, mariuszpos commented
> @mariuszpos You forgot to add [nrf fromtree] tag sauce in the commit message.

Done

2021-06-17 08:34 UTC, tejlmand approved these changes

2021-06-17 09:59 UTC, nvlsianpu approved these changes

2021-06-18 18:42 UTC, mbolivar-nordic approved these changes

2021-06-18 18:42 UTC, merged