mcuboot: Only include pcd.h when CONFIG_NRF53_UPGRADE_NETWORK_CORE is defined
nrfconnect/sdk-mcuboot pull request #157
Opened 2021-06-22 11:05 UTC by osaether

Only include pcd.h in mcuboot when CONFIG_NRF53_UPGRADE_NETWORK_CORE is defined

ref: NCSDK-7433

Signed-off-by: Ole Sæther <ole.saether@nordicsemi.no>

2021-06-22 14:47 UTC, sigvartmh approved these changes

2021-06-22 19:37 UTC, nvlsianpu approved these changes

2021-06-24 07:06 UTC, hakonfam requested changes

2021-06-24 07:06 UTC, hakonfam commented on boot/bootutil/src/loader.c
> +defined(CONFIG_NRF53_UPGRADE_NETWORK_CORE)
```suggestion
    defined(CONFIG_NRF53_UPGRADE_NETWORK_CORE)
```

2021-06-24 07:06 UTC, hakonfam commented on boot/zephyr/main.c
> +defined(CONFIG_NRF53_UPGRADE_NETWORK_CORE)
```suggestion
    defined(CONFIG_NRF53_UPGRADE_NETWORK_CORE)
```

2021-06-24 07:50 UTC, hakonfam approved these changes

2021-06-30 16:40 UTC, jfischer-no commented
Is not sauce tag missing here?

2021-06-30 16:56 UTC, nvlsianpu requested changes
^^

2021-07-02 15:20 UTC, nvlsianpu approved these changes

2021-07-02 15:22 UTC, nvlsianpu commented
manifest?

2021-07-05 10:39 UTC, osaether commented
> manifest?

https://github.com/nrfconnect/sdk-nrf/pull/5068

2021-07-14 10:39 UTC, merged