doc: MCUboot doc fixes
nrfconnect/sdk-mcuboot pull request #164
Opened 2021-08-11 16:28 UTC by FrancescoSer

Fixed note formatting.
Fixed typos in release notes.
Fixed case in chapter titles.
Removed contractions.
Fixed various spellings uncompliant with ncs doc guidelines.
Fixed references to flashing instead of programming.
Fixed commands formatting in Zephyr test plan.
Fixed references to doc folder in imgtool.md.
Removed mentions to Fabio Utzig in MCUboot sec policy as he left the company.
Connected to JIRA NCSDK 10376

Signed-off-by: Francesco Servidio <francesco.servidio@nordicsemi.no>

2021-08-11 16:41 UTC, FrancescoSer commented
This is a test to see how an edit to the docs in the mcuboot repo would look like.
There is a wrapper folder in ncs that also wraps rst files inside the mcuboot docs. 
(for reference: \ncs\nrf\doc\mcuboot\wrapper.rst )

I'm wondering if that folder shouldn't be the preferred way to edit the mcuboot docs, instead of editing .md files.

2021-08-17 08:10 UTC, peknis requested changes

2021-08-17 08:10 UTC, peknis commented on docs/release.md
>  the changes, not a list of the git commits.
```suggestion
Before making a release, update the `docs/release-notes.md`
to describe the release. This should be a high-level description of
the changes, not a list of the git commits.
```

2021-08-17 08:10 UTC, peknis commented on docs/release.md
>  Prior to each release, tags are made (see below) for at least one
```suggestion
Before each release, tags are made (see below) for at least one
```

2021-08-17 08:10 UTC, peknis commented on docs/release.md
>  time, and allow testing to happen.
```suggestion
the official a.b.c release). The intent is to freeze the code for a
time, and allow testing.
```

2021-08-17 08:10 UTC, peknis commented on docs/release.md
>  fetching from origin.  Typically, the releaser should create a branch
```suggestion
To make a release, make sure your local repo is on the tip version by
fetching from origin. Typically, the releaser should create a branch
```

2021-08-17 08:10 UTC, peknis commented on docs/testplan-mynewt.md
> +If testing RSA/PSS `newt create-image` needs to be passed in the extra flag `--rsa-pss`, for example:
```suggestion
If testing RSA/PSS, `newt create-image` needs to be passed in the extra flag `--rsa-pss`, for example:
```

2021-08-17 08:10 UTC, peknis commented on docs/testplan-zephyr.md
>  testing is done with the code in `samples/zephyr`.  These examples
```suggestion
The following roughly describes how MCUboot is tested on Zephyr. The
testing is performed with the code in `samples/zephyr`. These examples
```

2021-08-17 08:10 UTC, peknis commented on docs/release-notes.md
>  updated independently.  With this, it also supports additions to the
```suggestion
The 1.4.0 release of MCUboot primarily adds support for multi-image
booting. With this release, MCUboot can manage two images that can be
updated independently. It also supports additions to the
```

2021-08-17 08:10 UTC, peknis commented on docs/release-notes.md
>  if needed to address any issues.  There also may be branch releases of
```suggestion
This release of MCUboot works the Zephyr "main" at the time of the
release. It was tested as of hash `1a89ca1238`. When Zephyr v2.3.0 is
released, there will be a possible 1.6.1 or similar release of Zephyr
if needed to address any issues. There also may be branch releases of
```

2021-08-17 08:10 UTC, peknis commented on docs/release-notes.md
> +- CBOR decoding in serial recovery replaced by code generated from a CDDL description.
```suggestion
- CBOR decoding in serial recovery is replaced by code generated from a CDDL description.
```

2021-09-06 13:53 UTC, FrancescoSer commented
@peknis Thank you for your feedback, however this was just a draft to test how the edits would look like in NCS.
Since it was later decided to contribute upstream, I opened this PR in the MCUboot repo instead:

https://github.com/mcu-tools/mcuboot/pull/1129

Also, it is still in draft. More edits are to come, but I'm waiting for some feedback from the MCUboot maintainers first.

2021-09-06 13:54 UTC, closed without merging