[nrf fromtree] Allow to boot primary image if secondary one is unreachable
nrfconnect/sdk-mcuboot pull request #171
Opened 2021-08-31 12:07 UTC by nvlsianpu

Parent PR: https://github.com/mcu-tools/mcuboot/pull/1038

In case secondary image device has a malfunction,
It might be still possible to boot the primary image.

This make sense especially if the secondary image resides in an
external flash which might be damaged while SoC is still working.

2021-08-31 12:17 UTC, de-nordic approved these changes

2021-09-02 10:27 UTC, SebastianBoe requested changes

2021-09-02 10:27 UTC, SebastianBoe commented on boot/bootutil/src/loader.c
> +        }
The if-statement above uses a different coding convention

if
{
}

if {
}

2021-09-02 10:31 UTC, SebastianBoe commented on boot/bootutil/src/loader.c
> +        }
Already committed upstream.

Not worth the git paperwork to fix.

2021-09-02 10:31 UTC, SebastianBoe approved these changes

2021-09-02 10:45 UTC, merged