[nrf noup] zephyr: Fix serial recovery skipping on nrf53
nrfconnect/sdk-mcuboot pull request #189
Opened 2021-12-06 15:18 UTC by rakons

The nRF53 mcu has moved RESETREAS register
(from POWER to RESET peripheral).
This fix uses nrfx helper to select the proper register.

Signed-off-by: Radoslaw Koppel <radoslaw.koppel@nordicsemi.no>

2021-12-06 15:52 UTC, MarekPieta approved these changes

2021-12-07 09:26 UTC, jhn-nordic approved these changes

2021-12-07 10:21 UTC, nvlsianpu requested changes
this should go as [nrf fromlist]

2021-12-07 10:57 UTC, rakons commented
Correct upstream: mcu-tools/mcuboot#1234

2021-12-07 11:28 UTC, nvlsianpu approved these changes

2021-12-07 17:34 UTC, merged