PM partitioning for the Direct Xip mode
nrfconnect/sdk-mcuboot pull request #193
Opened 2022-02-01 11:20 UTC by kapi-no

Introduced partition description in order to support MCUboot's direct-xip mode.

2022-02-07 10:35 UTC, nvlsianpu requested changes

2022-02-07 10:35 UTC, nvlsianpu commented on boot/zephyr/pm.yml
> +#if CONFIG_BOOT_USING_SCRATCH
```suggestion
#if CONFIG_BOOT_SWAP_USING_SCRATCH
```

2022-02-07 13:48 UTC, kapi-no commented on boot/zephyr/pm.yml
> +#if CONFIG_BOOT_USING_SCRATCH
fixed

2022-02-07 14:43 UTC, kapi-no commented on boot/zephyr/pm.yml
> +#else
```suggestion
#endif

#if defined(CONFIG_BOOT_DIRECT_XIP)
```

2022-02-11 18:11 UTC, mbolivar-nordic commented
Please rebase onto the new history in main

2022-05-10 06:33 UTC, kapi-no commented
Rebased after upmerge. The diff is the same

2022-05-12 07:34 UTC, nvlsianpu approved these changes

2022-05-12 07:51 UTC, de-nordic approved these changes

2022-05-12 11:25 UTC, merged