Now it's possible to update the network core when NSIB is enabled
nrfconnect/sdk-mcuboot pull request #202
Opened 2022-05-12 16:20 UTC by simon-iversen

If CONFIG_SECURE_BOOT is enabled in the app core, mcuboot will check whether the image in the secondary slot is an mcuboot update or an app update. If the image belongs to the network core none of these will be the case, and it will return BOOT_SWAP_TYPE_NONE, and the network core update will fail.

By checking the reset address, these lines of codes can be skipped when the image belongs to the network core.

2022-05-12 17:32 UTC, sigvartmh commented
Add a title to the commit in the form of 

[nrf noup] bootutil: loader: Add check for network core address when NSIB is enabled (maybe this title is too long)

Content should be something like:

This enables network core updates when NSIB and MCUBoot are enabled.

Ref. NCSIDB-696

2022-05-13 09:57 UTC, sigvartmh requested changes
Code is okei, commit message needs a fixup.

2022-05-16 07:32 UTC, sigvartmh approved these changes

2022-05-16 07:34 UTC, sigvartmh commented
Still needs a bit clean up in history, you now have 3 commits should be 1. If you don't want to maintain this I can take it over just ping me.

You could do `git rebase -i HEAD~3` in your local repository then drop 2 of the commits.

a3b29db1378c246d0e75edc1aff2b4b4d465183a
060c83d6355e95cbb6d6faf58b115c966a92b6c5

2022-05-16 11:48 UTC, simon-iversen commented
Does it look good now?

> If you don't want to maintain this I can take it over just ping me.

One time has to be the first. It's nice to go through this and learn how it's done.

2022-05-17 12:15 UTC, nvlsianpu commented on boot/bootutil/src/loader.c
> -        int rc = flash_area_open(flash_area_id_from_multi_image_slot(
This would work for the network image pair, but its primary slot is emulated in RAM, therefore the flash_area doesn't have real offset.

2022-05-18 07:43 UTC, nvlsianpu commented
@simon-iversen Can you open manifest PR ASAP?

2022-05-18 12:22 UTC, simon-iversen commented
> @simon-iversen Can you open manifest PR ASAP?

https://github.com/nrfconnect/sdk-nrf/pull/7669

2022-05-19 14:14 UTC, nvlsianpu requested changes

2022-05-20 18:53 UTC, nvlsianpu approved these changes

2022-05-24 08:26 UTC, de-nordic approved these changes

2022-05-24 11:15 UTC, merged