[nrf nopu] boot/zephyr: add nrf54l15dk ext flash configs
nrfconnect/sdk-mcuboot pull request #360
Opened 2024-10-25 13:03 UTC by nvlsianpu

Copied configs from nrf54l15pdk.

2024-10-31 14:32 UTC, nordicjm commented on boot/zephyr/boards/nrf54l15dk_nrf54l15_cpuapp_ext_flash.conf
> +CONFIG_MULTITHREADING=y
*noup

2024-10-31 14:32 UTC, nordicjm approved these changes

2024-10-31 14:42 UTC, de-nordic approved these changes

2024-11-07 07:13 UTC, michalek-no commented
rebase

2024-11-07 07:32 UTC, nordicjm requested changes
erm, no, something amiss with your commits, 6 of them shouldn't be there

2024-11-07 09:17 UTC, nordicjm commented on boot/zephyr/Kconfig
> +	default BOOT_SIGNATURE_TYPE_ED25519 if SOC_NRF54L15_CPUAPP
this part needs to be a fixup of https://github.com/nrfconnect/sdk-mcuboot/commit/3cdcdb32f254248e6d2cd87dce09597723782562 in separate commit

2024-11-07 10:48 UTC, nordicjm approved these changes

2024-11-07 10:51 UTC, merged