zephyr: rename deprecated Kconfigs
nrfconnect/sdk-mcuboot pull request #379
Opened 2024-11-20 14:37 UTC by jasr93

The following Kconfigs have been replaced by the common
malloc implementation, rename them:

- `CONFIG_MINIMAL_LIBC_MALLOC`
- `CONFIG_MINIMAL_LIBC_CALLOC`
- `CONFIG_MINIMAL_LIBC_REALLOCARRAY`

Signed-off-by: Javier Santos <jasr93@outlook.es>

2025-05-15 10:12 UTC, de-nordic requested changes
Rebase needed.
The subject of commit should contain [nrf noup] tag, and the commit with change should be done as fixup for https://github.com/nrfconnect/sdk-mcuboot/commit/bc6443aa5223a817c3d86c4b9f1c8a1aa525098e

2025-06-10 14:25 UTC, gudnimg commented
Stumbled on this issue too, problem is still relevant in latest NCS SDK.

2025-06-10 14:39 UTC, nvlsianpu approved these changes

2025-07-04 08:10 UTC, closed without merging

2025-07-04 08:11 UTC, jasr93 commented
I've seen a new pull request merged with the same changes. It seems pointless to submit a pull request if it has been addressed or overwritten by other users.